<?php
// function custom_module_node_presave(\Drupal\node\NodeInterface $node) {
//   if ($node->getType() == 'page') {
//     // Append the keyword to the title 
//     $node->setTitle($node->getTitle() . ' TODAY WORK');
//     //dd($node->getTitle() );
//   }
//   d('This is a custom message edited');
//  \Drupal::messenger()->addMessage('This is a custom message');
// }

function custom_module_node_insert(\Drupal\node\NodeInterface $node){
  if ($node->getType() == 'article') {
   d('node inserted sucessfully');
  }
  //d('node inserted sucessfully');
}